import { StyleSheet } from 'react-native';
import { P } from '../constants/colors';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: P.bg },
  scroll: { flex: 1 },
  content: { paddingBottom: 40 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 22, paddingTop: 18, paddingBottom: 4 },
  headerKicker: { fontSize: 10, fontWeight: '700', letterSpacing: 1.6, color: P.navy },
  pageTitle: { fontSize: 38, fontWeight: '400', fontFamily: 'InstrumentSerif-Regular', color: P.text, lineHeight: 44, letterSpacing: -0.6, paddingHorizontal: 22, marginTop: 14, marginBottom: 18 },
  pageTitleItalic: { fontStyle: 'italic', fontFamily: 'InstrumentSerif-Italic', color: P.navy },
  chipsScroll: { marginBottom: 22 },
  chipsRow: { paddingHorizontal: 22, gap: 8, flexDirection: 'row', alignItems: 'center' },
  chip: { paddingHorizontal: 16, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: P.line, backgroundColor: P.surface },
  chipActive: { backgroundColor: P.navy, borderColor: P.navy },
  chipText: { fontSize: 13, fontWeight: '500', color: P.muted },
  chipTextActive: { color: P.white, fontWeight: '700' },
  featured: { backgroundColor: P.navy, borderRadius: 18, padding: 22, marginHorizontal: 22, marginBottom: 28 },
  featKicker: { fontSize: 10, fontWeight: '700', letterSpacing: 1.4, color: 'rgba(255,255,255,0.55)', marginBottom: 12 },
  featTitle: { fontSize: 14, fontWeight: '700', color: P.white, lineHeight: 25, marginBottom: 20 },
  featTitleItalic: { fontStyle: 'italic', fontFamily: 'InstrumentSerif-Italic', fontWeight: '400' },
  featAuthorRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  featAvatar: { width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  featAuthor: { fontSize: 12, color: 'rgba(255,255,255,0.65)', fontWeight: '500' },
  sectionLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 1.4, color: P.muted, marginBottom: 14, paddingHorizontal: 22 },
  catsRow: { flexDirection: 'row', gap: 8, marginBottom: 28, paddingHorizontal: 22 },
  catCard: { flex: 1, backgroundColor: P.surfaceAlt, borderRadius: 14, paddingVertical: 14, paddingHorizontal: 10, alignItems: 'center' },
  catLabel: { fontSize: 12, fontWeight: '700', color: P.text, marginBottom: 3, textAlign: 'center' },
  catCount: { fontSize: 10, color: P.muted, textAlign: 'center' },
  fichesTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 22, marginBottom: 6 },
  fichesTitleText: { fontSize: 17, fontWeight: '600', color: P.text },
  sortBtn: { flexDirection: 'row', alignItems: 'center' },
  sortText: { fontSize: 12, color: P.muted, fontWeight: '500' },
  articlesList: { paddingHorizontal: 22 },
  articleRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, gap: 14 },
  articleRowSep: { borderBottomWidth: 1, borderBottomColor: P.line },
  articleNum: { fontSize: 24, fontWeight: '300', color: P.muted, width: 34, textAlign: 'left', fontFamily: 'InstrumentSerif-Regular' },
  articleBody: { flex: 1 },
  articleMeta: { fontSize: 10, fontWeight: '700', letterSpacing: 1.2, color: P.muted, marginBottom: 4, textTransform: 'uppercase' },
  articleTitle: { fontSize: 15, fontWeight: '500', color: P.text, lineHeight: 21 },
});